if has("autocmd")
    filetype off
endif

" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

if has('vim_starting')
  set nocompatible               " Be iMproved
  set rtp+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My bundles
NeoBundle 'kana/vim-operator-user'
NeoBundle 'edkolev/erlang-motions.vim'
NeoBundle 'jimenezrick/vimerl'
NeoBundle 'sjl/gundo.vim'
NeoBundle 'derekwyatt/vim-scala'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'fatih/vim-go'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'the-lambda-church/merlin'
NeoBundle 'amdt/vim-niji'

call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

syntax on

set expandtab
set tabstop=4
set shiftwidth=4

set ofu=syntaxcomplete#Complete

" Set my mappings. Especially the capital W.
inoremap jj <Esc>
command W w
command Wq wq

if exists("&foldenable")
    set foldenable
endif

" colorscheme zenburn
" colorscheme desert

let g:haddock_browser="/usr/bin/chromium"
let g:haddock_browser_callformat="%s file://%s >/dev/null 2>&1 &"

" show tabs as double angle brackets
set list
set listchars=tab:»\ 

set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'

nmap <F8> :TagbarToggle<CR>

