# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000000
SAVEHIST=10000000
setopt appendhistory autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle :compinstall filename '/home/argentpyro//.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt hist_ignore_all_dups
setopt hist_ignore_space

### My Aliases ###
alias ls="ls --color"
alias brown='sudo wpa_supplicant -Dwext -iwlan0 -c/etc/wpa_supplicant/wpa_supplicant.conf'
alias nyan="nc -v miku.acm.uiuc.edu 23"          ## Fun little thing.
alias take-notes="vim notes-\`date +%a-%b-%d\`"  ## Create a new file to write notes
alias sp="vim +set\ buftype=nofile +startinsert" ## A quick scratchpad from the shell
alias -g LAUNCH=" &> /dev/null &disown"          ## Allow me to launch a program without worrying about output.
if which node &> /dev/null && which rlwrap &> /dev/null; then 
    alias node="env NODE_NO_READLINE=1 rlwrap node"; 
fi;

# Personal keybindings
bindkey -a "z" push-line

# prompt
autoload -U promptinit
promptinit

case "`hostname`" in
    "atlas")
        prompt gentoo
    ;;
    *) if (( $(zsh --version | cut -d ' ' -f 2 | cut -d '.' -f 3) < 10 )); then
        prompt adam1
    else 
        export PS1=$'%K{blue}%n@%m%k %B%F{cyan}%(4~|...|)%3~%F{yellow}$(parse_branch)%f%F{white}%(0?.. %F{red}(%?%)%f) %# %b%f%k'
    fi
    ;;
esac

# Environment variables
export EDITOR="vim"
export VISUAL="vim"
export LESS="-RX"

# More prompt
# via http://www.jukie.net/~bart/blog/20071219221358
typeset -ga precmd_functions
typeset -ga chpwd_functions
setopt prompt_subst
export __CUR_G_BRANCH=
parse_g_br() {
    git branch --no-color 2> /dev/null | \
        sed -e '/^[^*]/d' -e 's/* \(.*\)/ : \1/'
}
parse_h_br() {
    hg branch 2> /dev/null | sed -e 's/\(.*\)/ : \1/'
}
parse_branch() {
    parse_g_br 
    parse_h_br
}

# Check if there are any local settings
if [[ -f ~/.zshrc.local ]]; then
    . ~/.zshrc.local;
fi;

if which remind &> /dev/null; then
    remind ~/.reminders;
fi;
