# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1500
SAVEHIST=1500
setopt appendhistory autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle :compinstall filename '/home/argentpyro//.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt hist_ignore_all_dups
setopt hist_ignore_space
alias ls="ls --color"
alias brown='sudo wpa_supplicant -Dwext -iwlan0 -c/etc/wpa_supplicant/wpa_supplicant.conf'
alias nyan="nc -v miku.acm.uiuc.edu 23"

# prompt
autoload -U promptinit
promptinit

case "`hostname -s`" in
    atlas)
        prompt gentoo
        ;;

    *) if (( $(zsh --version | cut -d ' ' -f 2 | cut -d '.' -f 3) < 10 )); then
        prompt adam1
    else 
        export PS1=$'%K{blue}%n@%m%k %B%F{cyan}%(4~|...|)%3~%F{yellow}$(parse_branch)%f%F{white} %# %b%f%k'
    fi
    ;;
esac

export EDITOR="vim"
#
# Prompt
# via http://www.jukie.net/~bart/blog/20071219221358
typeset -ga precmd_functions
typeset -ga chpwd_functions
setopt prompt_subst
export __CUR_G_BRANCH=
parse_g_br() {
    git branch --no-color 2> /dev/null | \
        sed -e '/^[^*]/d' -e 's/* \(.*\)/ : \1/'
}
parse_h_br() {
    hg branch 2> /dev/null | sed -e 's/\(.*\)/ : \1/'
}
parse_branch() {
    parse_g_br 
    parse_h_br
}
precmd_functions+='precmd_update_g_vars'
#TODO: Make this a git hook?
#TODO: This runs if we hit return after a git command. However, pre-exec will
#not let us get the branch until after the command. Any fix?
precmd_update_g_vars() {
    case "$(history $(($HISTCMD-1)))" in (* g *|* git*)
        export __CUR_G_BRANCH="$(parse_g_br)"
        ;;
esac
}
chpwd_functions+='chpwd_update_g_vars'
chpwd_update_g_vars() { export __CUR_G_BRANCH="$(parse_g_br)" }
echo_g_br() { echo $__CUR_G_BRANCH }

# ex: mcomella@annyeong:iu/daebak:master:$

if [[ -f ~/.zshrc.local ]]; then
    . ~/.zshrc.local;
fi;

